version: "3.7"

networks:
  auth-network:
    driver: bridge

services:
  auth-server:
    image: quay.io/keycloak/keycloak:12.0.4
    container_name: auth-server
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      DB_VENDOR: postgres
      DB_ADDR: auth-db-server
      DB_USER: postgres
      DB_PASSWORD: password
      DB_DATABASE: keycloak
      DB_SCHEMA: public
      KEYCLOAK_IMPORT: /tmp/app.json
    ports:
      - 8080:8080
      - 8180:8080
    depends_on:
      - auth-db-server
    networks:
      - auth-network
    volumes:
      - ./keycloak/tmp:/tmp

  auth-db-server:
    build: ./db/postgresql
    container_name: auth-db-server
    restart: always
    tty: true
    ports:
      - 54330:5432
    volumes:
      - ./db/dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - auth-network
